'use client'

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  const queryClient = new QueryClient()
  return (
    <html lang="es">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className} suppressHydrationWarning={true}>
          <div className="flex flex-col gap-4 bg-gray-100 min-h-screen">

            {children}
          </div>
        </body>
      </QueryClientProvider>
    </html>
  )
}
